name: tako_dynamic_theme
description: A Flutter package for changing theme at a snap with persisting into the shared preferences. It is suitable for supporting multiple themes other than light and dark.
version: 0.0.2
homepage: https://github.com/wingstako/tako_dynamic_theme

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: '>=2.0.0 <3.0.0'

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter: 